### ISSUE TITLE
"Find Command(s)..." not responding

### ISSUE THREAD

**Issue by LisaCBrown** [OpenCDSS/cdss-app-tstool-main#98] opened 2019-08-12 16:30 UTC
### "Find Command(s)..." not responding###

I have a command file open. I right click in the command window and the pop-up menu appears. I select "Find Commands(s)...". The "Find" window appears. I type in a WDID (that is present in the file) and hit "enter". My mouse turns into the blue-spinning-wheel. No results are returned and the mouse remains the blue-spinning wheel. I am able to close the "Find" window and continue working in TSTool. I tried names and get the same behavior. Appears that the "Find" window is getting stuck and stops responding.

### Environment ###

* TSTool version 13.01.00
* Operating system = Windows 10 Pro

**Comment by smalers** [comment] 2019-08-12 16:34
I have duplicated this behavior.  I'll look into it.

**Comment by smalers** [comment] 2019-08-12 16:40
The issue is a cast between Command object and String, introduced when I cleaned up code awhile back to follow current Java guidelines.  I resolve and test.  This will go in a TSTool 13.01.01 release.

**Comment by smalers** [comment] 2019-08-12 17:28
I fixed the bug and uploaded TSTool 13.01.01 to the [download page](http://opencdss.state.co.us/tstool/).  Lisa, let me know how it goes.

**Comment by smalers** [comment] 2019-08-20 19:22
Having not heard from Lisa and I verified the fix myself, I am closing this issue.

**Closed by smalers** 2019-08-20 19:22 UTC
Labels: XS, bug, high
