### ISSUE TITLE
HydroBase datastore timeout - TSTool 14.2.2 

### ISSUE THREAD

**Issue by MMITISEK** [OpenCDSS/cdss-app-tstool-main#219] opened 2022-06-22 17:05 UTC
### Subject of the issue ###

HydroBase Time Out

**The content of this template can be replaced with that provided by the submitter.**

In version 14.2.2 the connection to HydroBase appears to time out, losing connection for any dependent commands.  Open/HydroBase.. does not appear to fix the issue and re-establish the connection.  Only completely closing TSTool and reopening allows the commands/HydroBase to be re-initialized

### Environment ###

* TSTool version 14.2.2
* Operating system version  - Windows 11
* See the ***Help / About TSTool*** menu item and ***Show Software/System Details*** for useful information.

### Steps to reproduce ###

Leave TSTool Open for an extended period, come back and Run All

### Expected Behavior ###

Commands/HydroBase to maintain the connection

### Actual Behavior ###

![image](https://user-images.githubusercontent.com/32108045/175093218-4d6c99c1-56f3-46fc-95f0-944b969c7287.png)

**Comment by MMITISEK** [comment] 2022-06-22 22:29
Steve -

I am thinking it is a bigger issue than just HydroBase timing out.  While
working on an active command file for a few hours all of a sudden the
commands that were working are throwing warnings.   The files I pulling
from are on Google Drive, so maybe that is the reason?  But obviously my
local HydroBase is not on Google Drive.   Again the only way to
reinitialize commands is to close and reopen TSTool.

So although this is an inconvenience it seems like there is a larger issue
going on for people that use the program for more than a few hours.

-Mark

Mark Mitisek, PH
Senior Project Manager | Integrated Modeling Practice Lead I Technology
Team Lead
Cell: 970-310-3835
***@***.***
<http://www.lrewater.com/>
LREWATER.COM <http://lrewater.com/>
1221 Auraria Parkway, Denver, CO 80204


***CONFIDENTIALITY NOTICE: This email message is for the sole use of the
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized review, use, disclosure, or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message. Thank
you.*

**Comment by smalers** [comment] 2022-10-05 17:52
I recently had to install software on a new Windows 11 machine, which was a good opportunity to see if there are any major changes.  I have had TSTool sitting overnight and it ran commands fine today.  I need Mark to let me know if this is still an issue because I don't know how to reproduce.  If he can provide a log file with exception stacks, it would be possible to see which code is having issues.

**Comment by smalers** [comment] 2022-10-21 15:29
From Mark:  For TSTool Version 14.3.0 I could not duplicate the commands "timing out".  Please close this issue.  If you would like me to go back to version 14.2.2 as a test, I can.  But I suspect it had something to do with my SQL server connection not TSTool.  I have completed a new install of HydroBase refreshing all SQL settings.  That may have fixed the issue.  I will let you know if it comes up again.

I am closing this issue.

**Closed by smalers** 2022-10-21 15:29 UTC
